// <auto-generated />
namespace Labinator2016R1.Lib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialBuild : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialBuild));
        
        string IMigrationMetadata.Id
        {
            get { return "201512262017278_InitialBuild"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
